apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker
  namespace: covidtracker
  labels:
    app: covidtracker
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: covidtracker
  template:
    metadata:
      labels:
        app: covidtracker
    spec:
      containers:
      - name: covidtracker
        envFrom:
        - secretRef:
            name: dbsecret
        image: marushovacr.azurecr.io/splinterzpm/covidtracker:28
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  namespace: covidtracker
data:
  db_root_username: ***REMOVED***
  db_root_password: ***REMOVED***
