apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: covidtracker
  labels:
    app: covidtracker
spec:
  selector:
    app: covidtracker
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covidtracker
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - backend:
          service: 
            name: ingress
            port:
              number: 443